/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarisKantor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DELL
 */
public class FormInventaris_diana extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form FormBarangMasuk_diana
     */
    public FormInventaris_diana() {
        initComponents();
        model = new DefaultTableModel();

        tabel_data.setModel(model);

        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Merk");
        model.addColumn("Jumlah");
        model.addColumn("Tanggal Masuk");
        loadData();
    }

    public final void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM tbl_inventaris";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("kd_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getString("kategori");
                o[3] = r.getString("merk");
                o[4] = r.getString("jumlah");
                o[5] = r.getString("tanggal_masuk");
                
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Kesalahan");
        }
    }
    
    public void kode() {
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM tbl_inventaris";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()) {
                String kdbarang = r.getString("kd_barang").substring(1);
                String AN = "" + (Integer.parseInt(kdbarang)+1);
                String Nol ="";
                
                if (AN.length()==1) {
                    Nol = "000";
                } else if (AN.length()==2) {
                    Nol = "00";
                } else if (AN.length()==3) {
                    Nol = "0";
                } else if (AN.length()==4) {
                    Nol = "";
                }
            
                kdbarang_diana.setText("L" + Nol + AN);
            } else {
                kdbarang_diana.setText("L0001");
            }
        } catch (Exception e) {
            System.out.println("Terjadi Kesalahan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        cari_diana = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        Label_kdbarang = new javax.swing.JLabel();
        Label_nmbarang = new javax.swing.JLabel();
        Label_kategori = new javax.swing.JLabel();
        Label_merk = new javax.swing.JLabel();
        Label_jumlah = new javax.swing.JLabel();
        kdbarang_diana = new javax.swing.JTextField();
        nmbarang_diana = new javax.swing.JTextField();
        kategori_diana = new javax.swing.JTextField();
        merk_diana = new javax.swing.JTextField();
        jumlah_diana = new javax.swing.JTextField();
        btn_simpan_diana = new javax.swing.JButton();
        btn_hapus_diana = new javax.swing.JButton();
        btn_edit_diana = new javax.swing.JButton();
        Panel_Background2 = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();
        btn_back_diana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAS - DIANA SARI");

        Panel_Background.setBackground(new java.awt.Color(204, 153, 255));

        Label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Label2.setText("List Data Inventaris Lualimastuff");

        Label3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label3.setText("Cari :");

        cari_diana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cari_dianaKeyReleased(evt);
            }
        });

        tabel_data.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data);

        Label_kdbarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_kdbarang.setText("Kode Barang");

        Label_nmbarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_nmbarang.setText("Nama Barang");

        Label_kategori.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_kategori.setText("Kategori");

        Label_merk.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_merk.setText("Merk");

        Label_jumlah.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_jumlah.setText("Jumlah");

        btn_simpan_diana.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_simpan_diana.setText("SIMPAN");
        btn_simpan_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_dianaActionPerformed(evt);
            }
        });

        btn_hapus_diana.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_hapus_diana.setText("HAPUS");
        btn_hapus_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_dianaActionPerformed(evt);
            }
        });

        btn_edit_diana.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_edit_diana.setText("EDIT");
        btn_edit_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_dianaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addComponent(Label2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label3)
                        .addGap(38, 38, 38)
                        .addComponent(cari_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addComponent(Label_jumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jumlah_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                            .addComponent(Label_merk)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(merk_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                            .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_kdbarang)
                                .addComponent(Label_nmbarang)
                                .addComponent(Label_kategori))
                            .addGap(40, 40, 40)
                            .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nmbarang_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kdbarang_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kategori_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(140, 140, 140)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_edit_diana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hapus_diana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_simpan_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Label2)
                .addGap(18, 18, 18)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_kdbarang)
                            .addComponent(kdbarang_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_nmbarang)
                            .addComponent(nmbarang_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kategori_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_kategori))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_merk)
                            .addComponent(merk_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_jumlah)
                            .addComponent(jumlah_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BackgroundLayout.createSequentialGroup()
                        .addComponent(btn_simpan_diana)
                        .addGap(20, 20, 20)
                        .addComponent(btn_hapus_diana)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit_diana)
                        .addGap(94, 94, 94)))
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label3)
                    .addComponent(cari_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Panel_Background2.setBackground(new java.awt.Color(153, 0, 204));
        Panel_Background2.setPreferredSize(new java.awt.Dimension(582, 81));

        Label.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setText("Data Inventaris Lualimastuff");

        btn_back_diana.setBackground(new java.awt.Color(255, 255, 255));
        btn_back_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_back_diana.setForeground(new java.awt.Color(255, 51, 51));
        btn_back_diana.setText("BACK");
        btn_back_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_dianaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Background2Layout = new javax.swing.GroupLayout(Panel_Background2);
        Panel_Background2.setLayout(Panel_Background2Layout);
        Panel_Background2Layout.setHorizontalGroup(
            Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(btn_back_diana)
                .addGap(29, 29, 29))
        );
        Panel_Background2Layout.setVerticalGroup(
            Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Background2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_back_diana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background2, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Background2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 506, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_dianaActionPerformed
        // TODO add your handling code here:
        FormMenu_diana fm = new FormMenu_diana();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_back_dianaActionPerformed

    private void cari_dianaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_dianaKeyReleased
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_inventaris WHERE kd_barang like '%" + cari_diana.getText() + "%' or nama_barang like'%" + cari_diana.getText() + "%'            or kategori like'" + cari_diana.getText() + "%' or merk like'%" + cari_diana.getText() + "%' " + "or jumlah like'%" + cari_diana.getText() + "%'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("kd_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getString("kategori");
                o[3] = r.getString("merk");
                o[4] = r.getString("jumlah");
                o[5] = r.getString("tanggal_masuk");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }//GEN-LAST:event_cari_dianaKeyReleased

    private void btn_simpan_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_dianaActionPerformed
        if (kdbarang_diana.getText().equals("") || nmbarang_diana.getText().equals("") || kategori_diana.getText().equals("") || merk_diana.getText().equals("") || jumlah_diana.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA!", "INVENTARIS LUALIMASTUFF", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String kdbarang = kdbarang_diana.getText();
            String nmbarang = nmbarang_diana.getText();
            String kategori = kategori_diana.getText();
            String merk = merk_diana.getText();
            String jumlah = jumlah_diana.getText();

            try {
                long millis=System.currentTimeMillis();
                java.sql.Date date=new java.sql.Date(millis);
                System.out.println(date);
                String tgl = date.toString();
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO tbl_inventaris VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kdbarang);
                p.setString(2, nmbarang);
                p.setString(3, kategori);
                p.setString(4, merk);
                p.setString(5, jumlah);
                p.setString(6, tgl);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Kesalahan");
            } finally {
                loadData();
                kode();

                nmbarang_diana.setText("");
                kategori_diana.setText("");
                merk_diana.setText("");
                jumlah_diana.setText("");

                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "INVENTARIS LUALIMASTUFF", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpan_dianaActionPerformed

    private void btn_hapus_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_dianaActionPerformed
        try {
            String sql ="delete from tbl_inventaris where kd_barang='"+kdbarang_diana.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        loadData();
        kdbarang_diana.setText("");
        nmbarang_diana.setText("");
        kategori_diana.setText("");
        merk_diana.setText("");
        jumlah_diana.setText("");
    }//GEN-LAST:event_btn_hapus_dianaActionPerformed

    private void btn_edit_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_dianaActionPerformed
        if(kdbarang_diana.getText().equals("") ||nmbarang_diana.getText().equals("") || kategori_diana.getText().equals("")|| merk_diana.getText().equals("")|| jumlah_diana.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "INVENTARIS LUALIMASTURR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int i = tabel_data.getSelectedRow();
            if (i == -1) {
                return;
            }
            String user = (String) model.getValueAt(i, 0);
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "UPDATE tbl_inventaris SET nama_barang = '" + nmbarang_diana.getText() + "', kategori='"+ kategori_diana.getText() + "', jumlah='"+ merk_diana.getText() + "', jumlah='"+ jumlah_diana.getText() +"' WHERE kd_barang ='" + kdbarang_diana.getText() + "'";
                PreparedStatement p = c.prepareStatement(sql);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Error");
            } finally {
                loadData();
                kdbarang_diana.setText("");
                nmbarang_diana.setText("");
                kategori_diana.setText("");
                merk_diana.setText("");
                jumlah_diana.setText("");
                btn_simpan_diana.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "INVENTARIS LUALIMASTUDD", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_edit_dianaActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        // TODO add your handling code here:
        btn_simpan_diana.setEnabled(false);
        btn_edit_diana.setEnabled(true);
        btn_hapus_diana.setEnabled(true);
        int i = tabel_data.getSelectedRow();

        if (i == -1) {
            return;
        }
        String kdbarang = (String) model.getValueAt(i, 0);
        kdbarang_diana.setText(kdbarang);
        kdbarang_diana.setEnabled(false);
        
        String nmbarang = (String) model.getValueAt(i, 1);
        nmbarang_diana.setText(nmbarang);
        
        String kategori = (String) model.getValueAt(i, 2);
        kategori_diana.setText(kategori);
        
        String merk = (String) model.getValueAt(i, 3);
        merk_diana.setText(merk);
        
        String jumlah = (String) model.getValueAt(i, 4);
        jumlah_diana.setText(jumlah);
    }//GEN-LAST:event_tabel_dataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInventaris_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInventaris_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInventaris_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInventaris_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInventaris_diana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label_jumlah;
    private javax.swing.JLabel Label_kategori;
    private javax.swing.JLabel Label_kdbarang;
    private javax.swing.JLabel Label_merk;
    private javax.swing.JLabel Label_nmbarang;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Background2;
    private javax.swing.JButton btn_back_diana;
    private javax.swing.JButton btn_edit_diana;
    private javax.swing.JButton btn_hapus_diana;
    private javax.swing.JButton btn_simpan_diana;
    private javax.swing.JTextField cari_diana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_diana;
    private javax.swing.JTextField kategori_diana;
    private javax.swing.JTextField kdbarang_diana;
    private javax.swing.JTextField merk_diana;
    private javax.swing.JTextField nmbarang_diana;
    private javax.swing.JTable tabel_data;
    // End of variables declaration//GEN-END:variables
}
