/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarisKantor;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class FormLogin_diana extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin_diana
     */
    public FormLogin_diana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        Panel_Backgrund2 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        username_diana = new javax.swing.JTextField();
        pass_diana = new javax.swing.JPasswordField();
        Label4 = new javax.swing.JLabel();
        btn_login_diana = new javax.swing.JButton();
        btn_logout_diana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAS - DIANA SARI");

        Panel_Background.setBackground(new java.awt.Color(255, 255, 255));

        Panel_Backgrund2.setBackground(new java.awt.Color(153, 0, 204));

        Label1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 255));
        Label1.setText("INVENTARIS LUALIMASTUFF");

        javax.swing.GroupLayout Panel_Backgrund2Layout = new javax.swing.GroupLayout(Panel_Backgrund2);
        Panel_Backgrund2.setLayout(Panel_Backgrund2Layout);
        Panel_Backgrund2Layout.setHorizontalGroup(
            Panel_Backgrund2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Backgrund2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(Label1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        Panel_Backgrund2Layout.setVerticalGroup(
            Panel_Backgrund2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Backgrund2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Label1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Label2.setText("SILAHKAN LOGIN TERLEBIH DAHULU");

        Label3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label3.setText("Username");

        pass_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_dianaActionPerformed(evt);
            }
        });

        Label4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label4.setText("Password");

        btn_login_diana.setBackground(new java.awt.Color(153, 0, 204));
        btn_login_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_login_diana.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_diana.setText("LOGIN");
        btn_login_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_dianaActionPerformed(evt);
            }
        });

        btn_logout_diana.setBackground(new java.awt.Color(153, 0, 204));
        btn_logout_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_logout_diana.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout_diana.setText("LOGOUT");

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Backgrund2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Label2))
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BackgroundLayout.createSequentialGroup()
                                .addComponent(btn_login_diana, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_logout_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Label4)
                            .addComponent(Label3)
                            .addComponent(username_diana)
                            .addComponent(pass_diana))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addComponent(Panel_Backgrund2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Label2)
                .addGap(34, 34, 34)
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_logout_diana, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_login_diana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_dianaActionPerformed
        // TODO add your handling code here:
        if(username_diana.getText().equals("") && pass_diana.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "username and password required !!");
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sql = stm.executeQuery("select * from tbl_login where username='" + username_diana.getText() + "' and password = '" + pass_diana.getText() + "'");
                    if (sql.next()) {
                        if (pass_diana.getText().equals(sql.getString("password"))) {
                        JOptionPane.showMessageDialog(null, "LOGIN Berhasil :)");
                        this.dispose();
                        FormMenu_diana fm = new FormMenu_diana();
                        fm.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Username dan Password SALAH!");
                        username_diana.setText("");
                        pass_diana.setText("");
                        username_diana.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Username dan Password TIDAK TERSEDIA!");
                        username_diana.setText("");
                        pass_diana.setText("");
                        username_diana.requestFocus();
                    }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "TERJADI KESALAHAN!!");
            }
        }

    }//GEN-LAST:event_btn_login_dianaActionPerformed

    private void pass_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_dianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_dianaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin_diana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Backgrund2;
    private javax.swing.JButton btn_login_diana;
    private javax.swing.JButton btn_logout_diana;
    private javax.swing.JPasswordField pass_diana;
    private javax.swing.JTextField username_diana;
    // End of variables declaration//GEN-END:variables
}
