/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarisKantor;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DELL
 */
public class FormLokasi_diana extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form FormLokasi_diana
     */
    public FormLokasi_diana() {
        initComponents();
        model = new DefaultTableModel();
        
        tabel_lokasi.setModel(model);
        model.addColumn("Kode Lokasi");
        model.addColumn("Nama Lokasi");
        loadData();
    }
    
    public final void loadData() {
        btn_simpan_diana.setEnabled(true);
        btn_hapus_diana.setEnabled(false);
        btn_edit_diana.setEnabled(false);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM tbl_lokasi";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o = new Object[2];
                o[0] = r.getString("kd_lokasi");
                o[1] = r.getString("nama_lokasi");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Kesalahan");
        }
    }
    
    public void kode() {
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM tbl_lokasi";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()) {
                String kdlokasi = r.getString("kd_lokasi").substring(1);
                String AN = "" + (Integer.parseInt(kdlokasi)+1);
                String Nol ="";
                
                if (AN.length()==1) {
                    Nol = "000";
                } else if (AN.length()==2) {
                    Nol = "00";
                } else if (AN.length()==3) {
                    Nol = "0";
                } else if (AN.length()==4) {
                    Nol = "";
                }
            
                kdlokasi_diana.setText("T" + Nol + AN);
            } else {
                kdlokasi_diana.setText("T0001");
            }
        } catch (Exception e) {
            System.out.println("Terjadi Kesalahan");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        Panel_Background2 = new javax.swing.JPanel();
        btn_back_diana = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        Label_kdlokasi = new javax.swing.JLabel();
        Label_nmlokasi = new javax.swing.JLabel();
        kdlokasi_diana = new javax.swing.JTextField();
        nmlokasi_diana = new javax.swing.JTextField();
        btn_simpan_diana = new javax.swing.JButton();
        btn_edit_diana = new javax.swing.JButton();
        btn_hapus_diana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_lokasi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAS - DIANA SARI");

        Panel_Background.setBackground(new java.awt.Color(204, 153, 255));

        Panel_Background2.setBackground(new java.awt.Color(153, 0, 204));

        btn_back_diana.setBackground(new java.awt.Color(255, 255, 255));
        btn_back_diana.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_back_diana.setForeground(new java.awt.Color(255, 51, 51));
        btn_back_diana.setText("BACK");
        btn_back_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_dianaActionPerformed(evt);
            }
        });

        Label.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setText("Data Lokasi");

        javax.swing.GroupLayout Panel_Background2Layout = new javax.swing.GroupLayout(Panel_Background2);
        Panel_Background2.setLayout(Panel_Background2Layout);
        Panel_Background2Layout.setHorizontalGroup(
            Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back_diana)
                .addGap(22, 22, 22))
        );
        Panel_Background2Layout.setVerticalGroup(
            Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Background2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Background2Layout.createSequentialGroup()
                        .addComponent(Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_Background2Layout.createSequentialGroup()
                        .addComponent(btn_back_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Label_kdlokasi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_kdlokasi.setText("Kode Lokasi");

        Label_nmlokasi.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Label_nmlokasi.setText("Nama Lokasi");

        btn_simpan_diana.setBackground(new java.awt.Color(153, 0, 204));
        btn_simpan_diana.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btn_simpan_diana.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan_diana.setText("SIMPAN");
        btn_simpan_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_dianaActionPerformed(evt);
            }
        });

        btn_edit_diana.setBackground(new java.awt.Color(153, 0, 204));
        btn_edit_diana.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btn_edit_diana.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_diana.setText("EDIT");
        btn_edit_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_dianaActionPerformed(evt);
            }
        });

        btn_hapus_diana.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus_diana.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btn_hapus_diana.setForeground(new java.awt.Color(255, 51, 51));
        btn_hapus_diana.setText("HAPUS");
        btn_hapus_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_dianaActionPerformed(evt);
            }
        });

        tabel_lokasi.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tabel_lokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_lokasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_lokasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_lokasi);

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_kdlokasi)
                            .addComponent(Label_nmlokasi))
                        .addGap(41, 41, 41)
                        .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                                .addComponent(btn_simpan_diana)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_hapus_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kdlokasi_diana)
                            .addComponent(nmlokasi_diana)))
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addComponent(Panel_Background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_kdlokasi)
                    .addComponent(kdlokasi_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nmlokasi)
                    .addComponent(nmlokasi_diana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan_diana)
                    .addComponent(btn_edit_diana)
                    .addComponent(btn_hapus_diana))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_dianaActionPerformed
        // TODO add your handling code here:
        FormMenu_diana fm = new FormMenu_diana();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_back_dianaActionPerformed

    private void btn_simpan_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_dianaActionPerformed
        // TODO add your handling code here:
        if (kdlokasi_diana.getText().equals("") || nmlokasi_diana.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA!", "INVENTARIS LUALIMASTUFF", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String kdlokasi = kdlokasi_diana.getText();
            String nmlokasi = nmlokasi_diana.getText();

            try {
                long millis=System.currentTimeMillis();
                java.sql.Date date=new java.sql.Date(millis);
                System.out.println(date);
                String tgl = date.toString();
                Connection c = koneksi.getKoneksi();
                String sql = "INSERT INTO tbl_lokasi VALUES (?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kdlokasi);
                p.setString(2, nmlokasi);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Kesalahan");
            } finally {
                loadData();
                kode();

                kdlokasi_diana.setText("");
                nmlokasi_diana.setText("");
                
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "INVENTARIS LUALIMASTUFF", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpan_dianaActionPerformed

    private void btn_edit_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_dianaActionPerformed
        // TODO add your handling code here:
        if (kdlokasi_diana.getText().equals("") || nmlokasi_diana.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "INVENTARIS LUALIMASTURR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int i = tabel_lokasi.getSelectedRow();
            if (i == -1) {
                return;
            }
            String lokasi = (String) model.getValueAt(i, 0);
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "UPDATE tbl_lokasi SET nama_lokasi = '" + nmlokasi_diana.getText() + "' WHERE kd_lokasi ='" + kdlokasi_diana.getText() + "'";
                PreparedStatement p = c.prepareStatement(sql);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Error");
            } finally {
                loadData();
                kdlokasi_diana.setText("");
                nmlokasi_diana.setText("");
                btn_simpan_diana.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "INVENTARIS LUALIMASTUDD", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_edit_dianaActionPerformed

    private void btn_hapus_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_dianaActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from tbl_lokasi where kd_lokasi='" + kdlokasi_diana.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        loadData();
        kdlokasi_diana.setText("");
        nmlokasi_diana.setText("");
    }//GEN-LAST:event_btn_hapus_dianaActionPerformed

    private void tabel_lokasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_lokasiMouseClicked
        // TODO add your handling code here:
        btn_simpan_diana.setEnabled(false);
        btn_edit_diana.setEnabled(true);
        btn_hapus_diana.setEnabled(true);
        int i = tabel_lokasi.getSelectedRow();

        if (i == -1) {
            return;
        }
        String kdlokasi = (String) model.getValueAt(i, 0);
        kdlokasi_diana.setText(kdlokasi);
        kdlokasi_diana.setEnabled(false);
        
        String nmlokasi = (String) model.getValueAt(i, 1);
        nmlokasi_diana.setText(nmlokasi);
    }//GEN-LAST:event_tabel_lokasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLokasi_diana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label_kdlokasi;
    private javax.swing.JLabel Label_nmlokasi;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Background2;
    private javax.swing.JButton btn_back_diana;
    private javax.swing.JButton btn_edit_diana;
    private javax.swing.JButton btn_hapus_diana;
    private javax.swing.JButton btn_simpan_diana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kdlokasi_diana;
    private javax.swing.JTextField nmlokasi_diana;
    public javax.swing.JTable tabel_lokasi;
    // End of variables declaration//GEN-END:variables
}
