/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarisKantor;
import java.awt.Desktop;
import java.net.URL;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class FormMenu_diana extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu_diana
     */
    public FormMenu_diana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        Panel_Background2 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label_DianaSari = new javax.swing.JLabel();
        Label_uas = new javax.swing.JLabel();
        menu_diana = new javax.swing.JMenuBar();
        Master_diana = new javax.swing.JMenu();
        pegawai_diana = new javax.swing.JMenuItem();
        inventaris_diana = new javax.swing.JMenuItem();
        tempat_diana = new javax.swing.JMenuItem();
        Transaksi_diana = new javax.swing.JMenu();
        b_masuk_diana = new javax.swing.JMenuItem();
        b_keluar_diana = new javax.swing.JMenuItem();
        laporan_diana = new javax.swing.JMenu();
        lap_masuk_diana = new javax.swing.JMenuItem();
        lap_keluar_diana = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAS - DIANA SARI");

        Panel_Background.setBackground(new java.awt.Color(204, 153, 255));

        Panel_Background2.setBackground(new java.awt.Color(153, 0, 204));
        Panel_Background2.setForeground(new java.awt.Color(255, 255, 255));

        Label1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 255));
        Label1.setText("INVENTARIS LUALIMASTUFF");

        javax.swing.GroupLayout Panel_Background2Layout = new javax.swing.GroupLayout(Panel_Background2);
        Panel_Background2.setLayout(Panel_Background2Layout);
        Panel_Background2Layout.setHorizontalGroup(
            Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Background2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(Label1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        Panel_Background2Layout.setVerticalGroup(
            Panel_Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Background2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Label1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Label_DianaSari.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_DianaSari.setForeground(new java.awt.Color(255, 255, 255));
        Label_DianaSari.setText("DIANA SARI - 21552011445");

        Label_uas.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Label_uas.setForeground(new java.awt.Color(255, 255, 255));
        Label_uas.setText("UJIAN AKHIR SEMESTER");

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(Label_DianaSari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_uas)
                .addGap(264, 264, 264))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Panel_Background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_DianaSari)
                .addGap(18, 18, 18)
                .addComponent(Label_uas)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        menu_diana.setBackground(new java.awt.Color(153, 0, 204));
        menu_diana.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        Master_diana.setText("Master");
        Master_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N

        pegawai_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        pegawai_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        pegawai_diana.setText("Pegawai");
        pegawai_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawai_dianaActionPerformed(evt);
            }
        });
        Master_diana.add(pegawai_diana);

        inventaris_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        inventaris_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        inventaris_diana.setText("Data Barang");
        inventaris_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventaris_dianaActionPerformed(evt);
            }
        });
        Master_diana.add(inventaris_diana);

        tempat_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        tempat_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        tempat_diana.setText("Data Lokasi");
        tempat_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempat_dianaActionPerformed(evt);
            }
        });
        Master_diana.add(tempat_diana);

        menu_diana.add(Master_diana);

        Transaksi_diana.setText("Transaksi");
        Transaksi_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N

        b_masuk_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        b_masuk_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        b_masuk_diana.setText("Barang Masuk");
        b_masuk_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_masuk_dianaActionPerformed(evt);
            }
        });
        Transaksi_diana.add(b_masuk_diana);

        b_keluar_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        b_keluar_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        b_keluar_diana.setText("Barang Keluar");
        b_keluar_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_keluar_dianaActionPerformed(evt);
            }
        });
        Transaksi_diana.add(b_keluar_diana);

        menu_diana.add(Transaksi_diana);

        laporan_diana.setText("Laporan");
        laporan_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N

        lap_masuk_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        lap_masuk_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        lap_masuk_diana.setText("Laporan Barang Masuk");
        lap_masuk_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_masuk_dianaActionPerformed(evt);
            }
        });
        laporan_diana.add(lap_masuk_diana);

        lap_keluar_diana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        lap_keluar_diana.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        lap_keluar_diana.setText("Laporan Barang Keluar");
        lap_keluar_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_keluar_dianaActionPerformed(evt);
            }
        });
        laporan_diana.add(lap_keluar_diana);

        menu_diana.add(laporan_diana);

        setJMenuBar(menu_diana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pegawai_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawai_dianaActionPerformed
        // TODO add your handling code here:
        FormPegawai_diana fp = new FormPegawai_diana();
        fp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pegawai_dianaActionPerformed

    private void inventaris_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventaris_dianaActionPerformed
        // TODO add your handling code here:
        FormInventaris_diana fi = new FormInventaris_diana();
        fi.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_inventaris_dianaActionPerformed

    private void b_masuk_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_masuk_dianaActionPerformed
        // TODO add your handling code here:
        FormBarangMasuk_diana fm = new FormBarangMasuk_diana();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_masuk_dianaActionPerformed

    private void b_keluar_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_keluar_dianaActionPerformed
        // TODO add your handling code here:
        FormBarangKeluar_diana fk = new FormBarangKeluar_diana();
        fk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_keluar_dianaActionPerformed

    private void tempat_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempat_dianaActionPerformed
        // TODO add your handling code here:
        FormLokasi_diana fl = new FormLokasi_diana();
        fl.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_tempat_dianaActionPerformed

    private void lap_masuk_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_masuk_dianaActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("http://localhost/InventarisLualimastuff/print.php").toURI());
        } catch (Exception e) {
            System.out.println(e);
        }    
    }//GEN-LAST:event_lap_masuk_dianaActionPerformed

    private void lap_keluar_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_keluar_dianaActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("http://localhost/InventarisLualimastuff/lapbarangkeluar.php").toURI());
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_lap_keluar_dianaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu_diana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label_DianaSari;
    private javax.swing.JLabel Label_uas;
    private javax.swing.JMenu Master_diana;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Background2;
    private javax.swing.JMenu Transaksi_diana;
    private javax.swing.JMenuItem b_keluar_diana;
    private javax.swing.JMenuItem b_masuk_diana;
    private javax.swing.JMenuItem inventaris_diana;
    private javax.swing.JMenuItem lap_keluar_diana;
    private javax.swing.JMenuItem lap_masuk_diana;
    private javax.swing.JMenu laporan_diana;
    private javax.swing.JMenuBar menu_diana;
    private javax.swing.JMenuItem pegawai_diana;
    private javax.swing.JMenuItem tempat_diana;
    // End of variables declaration//GEN-END:variables
}
