/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventarisKantor;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import InventarisKantor.FormBarangMasuk_diana;
/**
 *
 * @author DELL
 */
public class PopupLokasi_diana extends javax.swing.JFrame {
    DefaultTableModel model;
       
    public FormBarangMasuk_diana lokasi = null;
    /**
     * Creates new form PopupLokasi_diana
     */
    public PopupLokasi_diana() {
        initComponents();
        model = new DefaultTableModel();
        
        tabel_lokasi.setModel(model);
        model.addColumn("Kode Lokasi");
        model.addColumn("Nama Lokasi");
        loadData();
    }
    
    private void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM tbl_lokasi";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o = new Object[2];
                o[0] = r.getString("kd_lokasi");
                o[1] = r.getString("nama_lokasi");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Kesalahan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        cari_diana = new javax.swing.JTextField();
        btn_cari_diana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_lokasi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAS - DIANA SARI");

        Panel_Background.setBackground(new java.awt.Color(204, 153, 255));

        cari_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_dianaActionPerformed(evt);
            }
        });
        cari_diana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_dianaKeyPressed(evt);
            }
        });

        btn_cari_diana.setBackground(new java.awt.Color(153, 0, 204));
        btn_cari_diana.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        btn_cari_diana.setForeground(new java.awt.Color(255, 255, 255));
        btn_cari_diana.setText("CARI");
        btn_cari_diana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_dianaActionPerformed(evt);
            }
        });

        tabel_lokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_lokasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_lokasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_lokasi);

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                        .addComponent(cari_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cari_diana)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BackgroundLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_diana, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_diana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cari_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_dianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_dianaActionPerformed

    private void cari_dianaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_dianaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            loadData();
        }
    }//GEN-LAST:event_cari_dianaKeyPressed

    private void btn_cari_dianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_dianaActionPerformed
        loadData();
    }//GEN-LAST:event_btn_cari_dianaActionPerformed

    private void tabel_lokasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_lokasiMouseClicked
        int index = tabel_lokasi.getSelectedRow(); 
        lokasi.kdlokasi = tabel_lokasi.getValueAt(index, 0).toString();
        lokasi.nmlokasi = tabel_lokasi.getValueAt(index, 1).toString();
        lokasi.lokasiTerpilih();
        this.dispose();
    }//GEN-LAST:event_tabel_lokasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupLokasi_diana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupLokasi_diana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JButton btn_cari_diana;
    private javax.swing.JTextField cari_diana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_lokasi;
    // End of variables declaration//GEN-END:variables
}